version: "3.9"

networks:
  app:
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  postgres:
    image: postgres:13.3
    networks:
      app:
        ipv4_address: 172.21.0.5
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=172.21.0.5"
    ports:
      - "5433:5433" 
    environment:
      POSTGRES_DB: "userdata"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  server:
    depends_on:
      - postgres
    networks:
      app:
        ipv4_address: 172.21.0.6
    build: ./
    command: bash -c 'sleep 5; node server.js'
    ports:
      - "5003:5003"
    environment:
      DB_HOST: 172.21.0.5
    
    
    